package br.com.ivia.ceart.artesao.util.enums;

public enum Escolaridade {
	NAOALFABETIZADO,	//NÃO ALFABETIZADO
	FUNDAMENTAL1AO5,	//1 AO 5 ANO DO FUNDAMENTAL
	FUNDAMENTAL6AO9,	//6 AO 9 ANO DO FUNDAMENTAL
	MEDIOINCOMPLETO,	//ENSINO MEDIO INCOMPLETO
	MEDIOCOMPLETO,		//ENSINO MEDIO COMPLETO
	SUPERIORINCOMPLETO,	//SUPERIOR INCOMPLETO
	SUPERIORCOMPLETO,	//SUPERIOR COMPLETO
	POSGRADUACAO,		//POS-GRADUAÇÃO

}
