package br.com.ivia.ceart.artesao.util.enums;

public enum LocalVenda {
	CASAOFICINA,	//EM CASA E/OU OFICINA
	FEIRAS,			//EM FEIRAS
	NOCOMPRADOR,	//NO DOMICÍLIO DO COMPRADOR
	VIASPUBLICAS,	//VIAS PÚBLICAS (RUAS, PRAÇAS, ETC)
	SITE,			//SITE DE COMERCIALIZAÇÃO /COMÉRCIO ELETRÔNICO
	LOJAS,			//NAS LOJAS
	OUTROS;			//OUTROS
}
