package br.com.ivia.ceart.artesao.util.enums;

public enum Moradia {
	PROPRIA,		//PROPRIA
	FAVOR,			//DE FAVOR
	COMPARTILHADO,	//COMPARTILHADO
	CEDIDO,			//CEDIDO
	ARRENDADO,		//ARRENDADO
	ASSENTAMENTO,	//ASSENTAMENTO
	ALBERGUE,		//ALBERGUE
	ALUGUELSOCIAL,	//ALGUEL SOCIAL
	ALUGADO,		//ALUGADO
	OUTRO;			//OUTRA
}
